//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 04:10:44 PM GMT 
//


package _scale.schemas.accounts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _scale.schemas.accounts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _scale.schemas.accounts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link Accounts.Account }
     * 
     */
    public Accounts.Account createAccountsAccount() {
        return new Accounts.Account();
    }

    /**
     * Create an instance of {@link Accounts.Account.Users }
     * 
     */
    public Accounts.Account.Users createAccountsAccountUsers() {
        return new Accounts.Account.Users();
    }

    /**
     * Create an instance of {@link Accounts.Account.Plans }
     * 
     */
    public Accounts.Account.Plans createAccountsAccountPlans() {
        return new Accounts.Account.Plans();
    }

    /**
     * Create an instance of {@link Accounts.Account.Users.User }
     * 
     */
    public Accounts.Account.Users.User createAccountsAccountUsersUser() {
        return new Accounts.Account.Users.User();
    }

    /**
     * Create an instance of {@link Accounts.Account.Plans.Plan }
     * 
     */
    public Accounts.Account.Plans.Plan createAccountsAccountPlansPlan() {
        return new Accounts.Account.Plans.Plan();
    }

}
