//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 04:10:44 PM GMT 
//


package _scale.schemas.accounts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="org_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="credit_card_stored" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="plans">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="plan" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                                       &lt;element name="approval_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="end_user_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="setup_fee" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="cost_per_month" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="trial_period_days" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cancellation_period" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="users">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="user">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="account_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account"
})
@XmlRootElement(name = "accounts")
public class Accounts implements java.io.Serializable{

    protected List<Accounts.Account> account;

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accounts.Account }
     * 
     * 
     */
    public List<Accounts.Account> getAccount() {
        if (account == null) {
            account = new ArrayList<Accounts.Account>();
        }
        return this.account;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="org_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="credit_card_stored" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="plans">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="plan" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                             &lt;element name="approval_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="end_user_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="setup_fee" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="cost_per_month" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="trial_period_days" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cancellation_period" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="users">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="user">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="account_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "createdAt",
        "updatedAt",
        "state",
        "orgName",
        "extraFields",
        "creditCardStored",
        "plans",
        "users"
    })
    public static class Account implements java.io.Serializable {

        protected byte id;
        @XmlElement(name = "created_at", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createdAt;
        @XmlElement(name = "updated_at", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar updatedAt;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(name = "org_name", required = true)
        protected String orgName;
        @XmlElement(name = "extra_fields", required = true)
        protected String extraFields;
        @XmlElement(name = "credit_card_stored", required = true)
        protected String creditCardStored;
        @XmlElement(required = true)
        protected Accounts.Account.Plans plans;
        @XmlElement(required = true)
        protected Accounts.Account.Users users;

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(byte value) {
            this.id = value;
        }

        /**
         * Gets the value of the createdAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreatedAt() {
            return createdAt;
        }

        /**
         * Sets the value of the createdAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreatedAt(XMLGregorianCalendar value) {
            this.createdAt = value;
        }

        /**
         * Gets the value of the updatedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getUpdatedAt() {
            return updatedAt;
        }

        /**
         * Sets the value of the updatedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setUpdatedAt(XMLGregorianCalendar value) {
            this.updatedAt = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the orgName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgName() {
            return orgName;
        }

        /**
         * Sets the value of the orgName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgName(String value) {
            this.orgName = value;
        }

        /**
         * Gets the value of the extraFields property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtraFields() {
            return extraFields;
        }

        /**
         * Sets the value of the extraFields property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtraFields(String value) {
            this.extraFields = value;
        }

        /**
         * Gets the value of the creditCardStored property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreditCardStored() {
            return creditCardStored;
        }

        /**
         * Sets the value of the creditCardStored property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreditCardStored(String value) {
            this.creditCardStored = value;
        }

        /**
         * Gets the value of the plans property.
         * 
         * @return
         *     possible object is
         *     {@link Accounts.Account.Plans }
         *     
         */
        public Accounts.Account.Plans getPlans() {
            return plans;
        }

        /**
         * Sets the value of the plans property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accounts.Account.Plans }
         *     
         */
        public void setPlans(Accounts.Account.Plans value) {
            this.plans = value;
        }

        /**
         * Gets the value of the users property.
         * 
         * @return
         *     possible object is
         *     {@link Accounts.Account.Users }
         *     
         */
        public Accounts.Account.Users getUsers() {
            return users;
        }

        /**
         * Sets the value of the users property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accounts.Account.Users }
         *     
         */
        public void setUsers(Accounts.Account.Users value) {
            this.users = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="plan" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *                   &lt;element name="approval_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="end_user_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="setup_fee" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="cost_per_month" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="trial_period_days" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cancellation_period" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "plan"
        })
        public static class Plans implements java.io.Serializable {

            protected List<Accounts.Account.Plans.Plan> plan;

            /**
             * Gets the value of the plan property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the plan property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPlan().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Accounts.Account.Plans.Plan }
             * 
             * 
             */
            public List<Accounts.Account.Plans.Plan> getPlan() {
                if (plan == null) {
                    plan = new ArrayList<Accounts.Account.Plans.Plan>();
                }
                return this.plan;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
             *         &lt;element name="approval_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="end_user_required" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="setup_fee" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="cost_per_month" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="trial_period_days" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cancellation_period" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "name",
                "type",
                "state",
                "serviceId",
                "approvalRequired",
                "endUserRequired",
                "setupFee",
                "costPerMonth",
                "trialPeriodDays",
                "cancellationPeriod"
            })
            public static class Plan implements java.io.Serializable {

                protected byte id;
                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected String state;
                @XmlElement(name = "service_id")
                protected Byte serviceId;
                @XmlElement(name = "approval_required")
                protected String approvalRequired;
                @XmlElement(name = "end_user_required")
                protected String endUserRequired;
                @XmlElement(name = "setup_fee")
                protected float setupFee;
                @XmlElement(name = "cost_per_month")
                protected float costPerMonth;
                @XmlElement(name = "trial_period_days", required = true)
                protected String trialPeriodDays;
                @XmlElement(name = "cancellation_period")
                protected byte cancellationPeriod;
                @XmlAttribute(name = "default")
                protected String _default;
                @XmlAttribute(name = "custom")
                protected String custom;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public byte getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(byte value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the state property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getState() {
                    return state;
                }

                /**
                 * Sets the value of the state property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setState(String value) {
                    this.state = value;
                }

                /**
                 * Gets the value of the serviceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getServiceId() {
                    return serviceId;
                }

                /**
                 * Sets the value of the serviceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setServiceId(Byte value) {
                    this.serviceId = value;
                }

                /**
                 * Gets the value of the approvalRequired property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getApprovalRequired() {
                    return approvalRequired;
                }

                /**
                 * Sets the value of the approvalRequired property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setApprovalRequired(String value) {
                    this.approvalRequired = value;
                }

                /**
                 * Gets the value of the endUserRequired property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEndUserRequired() {
                    return endUserRequired;
                }

                /**
                 * Sets the value of the endUserRequired property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEndUserRequired(String value) {
                    this.endUserRequired = value;
                }

                /**
                 * Gets the value of the setupFee property.
                 * 
                 */
                public float getSetupFee() {
                    return setupFee;
                }

                /**
                 * Sets the value of the setupFee property.
                 * 
                 */
                public void setSetupFee(float value) {
                    this.setupFee = value;
                }

                /**
                 * Gets the value of the costPerMonth property.
                 * 
                 */
                public float getCostPerMonth() {
                    return costPerMonth;
                }

                /**
                 * Sets the value of the costPerMonth property.
                 * 
                 */
                public void setCostPerMonth(float value) {
                    this.costPerMonth = value;
                }

                /**
                 * Gets the value of the trialPeriodDays property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTrialPeriodDays() {
                    return trialPeriodDays;
                }

                /**
                 * Sets the value of the trialPeriodDays property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTrialPeriodDays(String value) {
                    this.trialPeriodDays = value;
                }

                /**
                 * Gets the value of the cancellationPeriod property.
                 * 
                 */
                public byte getCancellationPeriod() {
                    return cancellationPeriod;
                }

                /**
                 * Sets the value of the cancellationPeriod property.
                 * 
                 */
                public void setCancellationPeriod(byte value) {
                    this.cancellationPeriod = value;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the custom property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCustom() {
                    return custom;
                }

                /**
                 * Sets the value of the custom property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCustom(String value) {
                    this.custom = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="user">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="account_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "user"
        })
        public static class Users implements java.io.Serializable {

            @XmlElement(required = true)
            protected Accounts.Account.Users.User user;

            /**
             * Gets the value of the user property.
             * 
             * @return
             *     possible object is
             *     {@link Accounts.Account.Users.User }
             *     
             */
            public Accounts.Account.Users.User getUser() {
                return user;
            }

            /**
             * Sets the value of the user property.
             * 
             * @param value
             *     allowed object is
             *     {@link Accounts.Account.Users.User }
             *     
             */
            public void setUser(Accounts.Account.Users.User value) {
                this.user = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="account_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="extra_fields" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "createdAt",
                "updatedAt",
                "accountId",
                "state",
                "role",
                "username",
                "email",
                "extraFields"
            })
            public static class User implements java.io.Serializable {

                protected byte id;
                @XmlElement(name = "created_at", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar createdAt;
                @XmlElement(name = "updated_at", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar updatedAt;
                @XmlElement(name = "account_id")
                protected byte accountId;
                @XmlElement(required = true)
                protected String state;
                @XmlElement(required = true)
                protected String role;
                @XmlElement(required = true)
                protected String username;
                @XmlElement(required = true)
                protected String email;
                @XmlElement(name = "extra_fields", required = true)
                protected String extraFields;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public byte getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(byte value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the createdAt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getCreatedAt() {
                    return createdAt;
                }

                /**
                 * Sets the value of the createdAt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setCreatedAt(XMLGregorianCalendar value) {
                    this.createdAt = value;
                }

                /**
                 * Gets the value of the updatedAt property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getUpdatedAt() {
                    return updatedAt;
                }

                /**
                 * Sets the value of the updatedAt property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setUpdatedAt(XMLGregorianCalendar value) {
                    this.updatedAt = value;
                }

                /**
                 * Gets the value of the accountId property.
                 * 
                 */
                public byte getAccountId() {
                    return accountId;
                }

                /**
                 * Sets the value of the accountId property.
                 * 
                 */
                public void setAccountId(byte value) {
                    this.accountId = value;
                }

                /**
                 * Gets the value of the state property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getState() {
                    return state;
                }

                /**
                 * Sets the value of the state property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setState(String value) {
                    this.state = value;
                }

                /**
                 * Gets the value of the role property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRole() {
                    return role;
                }

                /**
                 * Sets the value of the role property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRole(String value) {
                    this.role = value;
                }

                /**
                 * Gets the value of the username property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUsername() {
                    return username;
                }

                /**
                 * Sets the value of the username property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUsername(String value) {
                    this.username = value;
                }

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

                /**
                 * Gets the value of the extraFields property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExtraFields() {
                    return extraFields;
                }

                /**
                 * Sets the value of the extraFields property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExtraFields(String value) {
                    this.extraFields = value;
                }

            }

        }

    }

}
